export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

//----------------AUTH--------------------
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAILURE = 'AUTH_SIGNOUT_FAILURE';



export const AUTH_ERROR = 'AUTH_ERROR';


//-------------PROJECTS---------------
export const PROJECT_CREATE = 'PROJECT_CREATE';